name: Autorelease

on:
  push:
    branches: [ release ]
    paths-ignore:
      - 'CHANGELOG.md'
env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Setup Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22.20.0
      
      - name: Release
        run: |
          npm ci
          npx semantic-release
      
      - name: Sync release artifacts
        uses: knowledgepixels/sync-release-artifacts-action@main
        with:
          main-branch: main
          release-branch: release
